# Copyright FUJITSU LIMITED 2014.

- name: install wget
  yum: name=wget state=latest

- name: install finger
  yum: name=finger state=latest

- name: install make
  yum: name=make state=latest

- name: install libevent
  yum: name=libevent state=latest

- name: install libevent-devel
  yum: name=libevent-devel state=latest

- name: install gcc
  yum: name=gcc state=latest


- name: download memcached-{{ memcached_version }}.tar.gz
#  1.4.15 <=
#  get_url: url=http://memcached.googlecode.com/files/memcached-{{ memcached_version }}.tar.gz dest=/usr/local/src/memcached-{{ memcached_version }}.tar.gz
#  1.4.16 >=
  get_url: url=http://www.memcached.org/files/memcached-{{ memcached_version }}.tar.gz dest=/usr/local/src/memcached-{{ memcached_version }}.tar.gz


- name: expand memcached-{{ memcached_version }}.tar.gz
  unarchive: src=/usr/local/src/memcached-{{ memcached_version }}.tar.gz dest=/usr/local/src copy=no

- name: memcached ã‚’ configure
  command: >
    ./configure
    --prefix=/opt/memcached-{{ memcached_version }}
    --enable-64bit
  args:
    chdir: /usr/local/src/memcached-{{ memcached_version }}
    creates: /usr/local/src/memcached-{{ memcached_version }}/Makefile

- name: compile memcached
  command: make
  args:
    chdir: /usr/local/src/memcached-{{ memcached_version }}
    creates: /usr/local/src/memcached-{{ memcached_version }}/memcached

- name: install memcached
  command: make install
  args:
    chdir: /usr/local/src/memcached-{{ memcached_version }}
    creates: /opt/memcached-{{ memcached_version }}

- name: change /opt/memcached-{{ memcached_version }}'s owner into memcached
  file: path=/opt/memcached-{{ memcached_version }} owner=memcached group=memcached recurse=yes
