# Copyright FUJITSU LIMITED 2014.

- name: crate /fj
  file: state=directory path=/fj owner=root group=root mode=0755


- name: crate /opt/disk1/dc-core
  file: state=directory path=/opt/disk1/dc-core owner=root group=root mode=0755

- name: crate /opt/disk1/dc-core/log
  file: state=directory path=/opt/disk1/dc-core/log owner=glassfish group=glassfish mode=0755

- name: crate /fj/dc-core
  file: state=directory path=/fj/dc-core owner=glassfish group=glassfish mode=0755

- name: create /opt/disk1/dc-core/log symlink named by /fj/dc-core
  file: state=link src=/opt/disk1/dc-core/log dest=/fj/dc-core/log owner=glassfish group=glassfish mode=0777

- name: crate /fj/dc-core/conf
  file: state=directory path=/fj/dc-core/conf owner=root group=root mode=0755

- name: crate /fj/dc-core/conf/18888
  file: state=directory path=/fj/dc-core/conf/18888 owner=root group=root mode=0755

- name: crate /fj/dc-core/conf/28888
  file: state=directory path=/fj/dc-core/conf/28888 owner=root group=root mode=0755

- name: crate /fj/dc-core/conf/38888
  file: state=directory path=/fj/dc-core/conf/38888 owner=root group=root mode=0755

- name: crate /fj/dc-core/conf/48888
  file: state=directory path=/fj/dc-core/conf/48888 owner=root group=root mode=0755

- name: crate /opt/disk1/dc-core/ads
  file: state=directory path=/opt/disk1/dc-core/ads owner=glassfish group=glassfish mode=0755

- name: create /opt/disk1/dc-core/ads symlink named by /fj/dc-core
  file: state=link src=/opt/disk1/dc-core/ads dest=/fj/dc-core/ads owner=glassfish group=glassfish mode=0777


- name: crate /opt/disk1/dc-engine
  file: state=directory path=/opt/disk1/dc-engine owner=root group=root mode=0755

- name: crate /opt/disk1/dc-engine/log
  file: state=directory path=/opt/disk1/dc-engine/log owner=glassfish group=glassfish mode=0755

- name: crate /fj/dc-engine
  file: state=directory path=/fj/dc-engine owner=glassfish group=glassfish mode=0755

- name: create /opt/disk1/dc-engine/log symlink named by /fj/dc-engine
  file: state=link src=/opt/disk1/dc-engine/log dest=/fj/dc-engine/log owner=glassfish group=glassfish mode=0777

- name: crate /fj/dc-engine/extensions
  file: state=directory path=/fj/dc-engine/extensions owner=glassfish group=glassfish mode=0755


- name: crate /opt/disk1/glassfish
  file: state=directory path=/opt/disk1/glassfish owner=glassfish group=glassfish mode=0755

- name: crate /opt/disk1/glassfish/log
  file: state=directory path=/opt/disk1/glassfish/log owner=glassfish group=glassfish mode=0755

- name: crate /fj/glassfish
  file: state=directory path=/fj/glassfish owner=glassfish group=glassfish mode=0755

- name: create /opt/disk1/glassfish/log symlink named by /fj/glassfish
  file: state=link src=/opt/disk1/glassfish/log dest=/fj/glassfish/log owner=glassfish group=glassfish mode=0777


- name: crate /fj/18888
  file: state=directory path=/fj/18888 owner=glassfish group=glassfish mode=0755

- name: crate /fj/18888/dc-engine
  file: state=directory path=/fj/18888/dc-engine owner=glassfish group=glassfish mode=0755

- name: crate /fj/18888/dc-engine/extensions
  file: state=directory path=/fj/18888/dc-engine/extensions owner=glassfish group=glassfish mode=0755

- name: crate /fj/28888
  file: state=directory path=/fj/28888 owner=glassfish group=glassfish mode=0755

- name: crate /fj/28888/dc-engine
  file: state=directory path=/fj/28888/dc-engine owner=glassfish group=glassfish mode=0755

- name: crate /fj/28888/dc-engine/extensions
  file: state=directory path=/fj/28888/dc-engine/extensions owner=glassfish group=glassfish mode=0755

- name: crate /fj/38888
  file: state=directory path=/fj/38888 owner=glassfish group=glassfish mode=0755

- name: crate/fj/38888/dc-engine
  file: state=directory path=/fj/38888/dc-engine owner=glassfish group=glassfish mode=0755

- name: crate /fj/38888/dc-engine/extensions
  file: state=directory path=/fj/38888/dc-engine/extensions owner=glassfish group=glassfish mode=0755

- name: crate /fj/48888
  file: state=directory path=/fj/48888 owner=glassfish group=glassfish mode=0755

- name: crate /fj/48888/dc-engine
  file: state=directory path=/fj/48888/dc-engine owner=glassfish group=glassfish mode=0755

- name: crate /fj/48888/dc-engine/extensions
  file: state=directory path=/fj/48888/dc-engine/extensions owner=glassfish group=glassfish mode=0755

